name = "ModelDefiner"
uuid = "b7b86668-839c-4d95-80f4-5c5068c32ec5"
authors = ["qfl3x <qfl3x@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
